name: Sync Docker Images
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login Aliyun ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_REGISTRY_USER }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      - name: Install skopeo
        run: sudo apt update && sudo apt install -y skopeo

      - name: Sync images via skopeo
        run: |
          while read src_img; do
            if [[ -n "$src_img" ]]; then
              dest_img="${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/${src_img//\//-}"
              skopeo copy --all docker://$src_img docker://$dest_img
            fi
          done < images.txt
