name: Sync Docker Images
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login Aliyun ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_REGISTRY_USER }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      - name: Sync images to ACR
        uses: skyrim-liu/image-sync-action@main
        env:
          DEST_REGISTRY: ${{ secrets.ALIYUN_REGISTRY }}
          DEST_NAMESPACE: ${{ secrets.ALIYUN_NAME_SPACE }}
          IMAGE_LIST_FILE: images.txt
