name: Sync Docker Images
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Sync images
        uses: docker://pengzhanbo/docker-image-pusher:latest
        env:
          ALIYUN_REGISTRY: ${{ secrets.ALIYUN_REGISTRY }}
          ALIYUN_REGISTRY_USER: ${{ secrets.ALIYUN_REGISTRY_USER }}
          ALIYUN_REGISTRY_PASSWORD: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
          ALIYUN_NAME_SPACE: ${{ secrets.ALIYUN_NAME_SPACE }}
